apiVersion: v1
kind: Secret
metadata:
  name: github-cred
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  password: GITHUB_PASSWORD
  username: GITHUB_USERNAME
